spring:
  application:
    name: monitoring-service
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: OMSUSER
    password: omsuserpass
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect
        use_sql_comments: false
        globally_quoted_identifiers: false
        jdbc:
          time_zone: UTC

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

security:
  filter:
    token-validation-url: http://localhost:8090/oauth2/rest/token/info
    strict-header-mode: true
    excluded-paths:
      - /actuator/**

logging:
  level:
    com.shdev.monitoringservice: DEBUG
    com.shdev.security: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} [%X{requestId}] [%X{userIdToken}] [%X{userIdHeader}] [%X{originService}] [%X{originApplication}] [%X{client}] - %msg%n"
